# This is the configuration file for your production environment.
# Angepasst für Docker-Container-Umgebung

# Configuration for the main API server.
apiServer:
  port: 8080
  publicHost: 159.69.144.208
  publicPort: 8080
  publicScheme: http

# Configuration for the Insights server.
insightsServer:
  port: 8081
  publicHost: 159.69.144.208
  publicPort: 8081
  publicScheme: http

# Configuration for the web server.
webServer:
  port: 8082
  publicHost: 159.69.144.208
  publicPort: 8082
  publicScheme: http

# Database setup für Docker Container
# Der Host 'postgres' ist der Container-Name im Docker-Netzwerk
database:
  host: postgres
  port: 5432
  name: test_db
  user: postgres
  requireSsl: false
  #isUnixSocket: false

# Redis deaktiviert für diese Setup
redis:
  enabled: false

maxRequestSize: 524288

sessionLogs:
  consoleEnabled: true

# futureCallExecutionEnabled: true

#futureCall:
#  concurrencyLimit: 1 # Defaults to 1, a negative or null value removes the limit
#  scanInterval: 5000 # Defaults to 5000
