name: vertic_server_server
description: Vertic Kassensystem - Serverpod Backend Server
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  serverpod: 2.8.0
  serverpod_auth_server: 2.8.0
  crypto: ^3.0.3
  bcrypt: ^1.1.3

dev_dependencies:
  lints: '>=3.0.0 <6.0.0'
  test: '^1.24.2'
  serverpod_test: 2.8.0
  serverpod_cli: 2.8.0

